name = "codefromanywhere"
compatibility_date = "2025-03-01"
dev.port = 3000
assets.directory = "./"
routes = [
  { pattern = "codefromanywhere.com", custom_domain = true },
  { pattern = "www.codefromanywhere.com", custom_domain = true }
]